[app]

title = ChatLite
package.name = chatlite
package.domain = org.chatlite

source.dir = .
source.include_exts = py,png,jpg,jpeg,kv,atlas

version = 1.0

requirements = python3,kivy,websockets

orientation = portrait
fullscreen = 0

android.permissions = INTERNET
android.accept_sdk_license = True

[buildozer]

log_level = 2
warn_on_root = 1
